# Generated by Django 4.0.3 on 2022-09-06 20:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectpage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project',
            field=wagtail.core.fields.StreamField([('label', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
