# Generated by Django 4.0.3 on 2022-04-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_blogpagetags_blogpagetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_image_excerpt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
