# Generated by Django 4.0.3 on 2022-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
