# Generated by Django 4.0.3 on 2022-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
