# Generated by Django 4.0.3 on 2022-09-26 19:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_above_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='below_posts',
            field=wagtail.core.fields.StreamField([('bottom_content', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('imageTwo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('content', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
