# Generated by Django 4.0.3 on 2023-04-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_above_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='above_posts',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='background_img',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='below_posts',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sub_headline',
        ),
    ]
